# __GENERATED__ makefile marker
#

include $(GNUSTEP_MAKEFILES)/common.make
-include ../GNUmakefile.super
-include Flags.mk

TEST_TOOL_NAME = general

ADDITIONAL_OBJCFLAGS += -I/brains99/gnu/devmodules/tests/testsuite -Wall

general_OBJC_FILES = general.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/test-tool.make

test:
	./$(GNUSTEP_OBJ_DIR_NAME)/general
