# __GENERATED__ makefile marker
#

include $(GNUSTEP_MAKEFILES)/common.make
-include ../GNUmakefile.super
-include Flags.mk

TEST_TOOL_NAME = @TESTNAME@

ADDITIONAL_OBJCFLAGS += -I@INCLUDEDIR@ -Wall

@TESTNAME@_OBJC_FILES = @FILENAME@

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/test-tool.make

test:
	./obj/@TESTNAME@
