#
#
#

include $(GNUSTEP_MAKEFILES)/common.make

-include ../GNUmakefile.super
-include GNUmakefile.mk

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/test-tool.make

-include GNUmakefile.postamble
