
include $(GNUSTEP_MAKEFILES)/common.make
BUNDLE_NAME = TestBundle
TestBundle_OBJC_FILES = TestBundle.m
include $(GNUSTEP_MAKEFILES)/bundle.make
include $(GNUSTEP_MAKEFILES)/test-tool.make

check::	all
