
include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = StatusServer

StatusServer_OBJC_FILES = StatusServer.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble

