
include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = processgroup testcat

processgroup_OBJC_FILES = processgroup.m
processgroup_NEEDS_GUI = NO

testcat_OBJC_FILES = testcat.m
testcat_NEEDS_GUI = NO

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble

