
include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = processgroup

processgroup_OBJC_FILES = processgroup.m
processgroup_NEEDS_GUI = NO

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble

