# __GENERATED__ makefile marker
#

include $(GNUSTEP_MAKEFILES)/common.make
-include ../GNUmakefile.super
-include Flags.mk

TEST_TOOL_NAME = NSSortDescriptorfg

ADDITIONAL_OBJCFLAGS += -I/brains99/gnu/devmodules/tests/testsuite -Wall

NSSortDescriptorfg_OBJC_FILES = NSSortDescriptorfg

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/test-tool.make

test:
	./$(GNUSTEP_OBJ_DIR_NAME)/NSSortDescriptorfg
