# __GENERATED__ makefile marker
#

include $(GNUSTEP_MAKEFILES)/common.make
-include ../GNUmakefile.super
-include Flags.mk

TEST_TOOL_NAME = NSTask

ADDITIONAL_OBJCFLAGS += -I/f/Development/Step/GNU/sbox/core/tests -Wall

NSTask_OBJC_FILES = NSTask

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/test-tool.make

test:
	./$(GNUSTEP_OBJ_DIR_NAME)/NSTask
