#
# Top-level base testsuite makefile
#
# Run this before loading any tests
#

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = GenericTests

-include GNUmakefile.preamble
ADDITIONAL_OBJCFLAGS += -Wall

include $(GNUSTEP_MAKEFILES)/aggregate.make

-include GNUmakefile.postamble
