
include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = capture respond

capture_OBJC_FILES = capture.m

respond_OBJC_FILES = respond.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble

